# Generated by Django 4.2 on 2023-05-12 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiers', models.CharField(max_length=255)),
                ('sequence', models.TextField()),
                ('score', models.FloatField()),
                ('thermophilic', models.BooleanField()),
                ('user_requst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.userrequest')),
            ],
        ),
    ]
