# Generated by Django 4.2 on 2023-05-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proteinsequence',
            old_name='user_requst',
            new_name='user_reqeust',
        ),
    ]
