# Generated by Django 4.2 on 2023-05-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_rename_user_requst_proteinsequence_user_reqeust'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proteinsequence',
            old_name='user_reqeust',
            new_name='user_request',
        ),
    ]
