# Generated by Django 4.2 on 2023-06-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_userrequest_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='request_id',
            new_name='request_ids',
        ),
    ]
