# Generated by Django 4.2 on 2023-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_rename_request_id_userrequest_request_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='number_of_seqeunces',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
