# Generated by Django 4.2 on 2023-06-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_userrequest_number_of_seqeunces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='request_ids',
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='number_of_seqeunces',
            field=models.IntegerField(default=0),
        ),
    ]
