# Generated by Django 4.2 on 2023-06-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_remove_userrequest_request_ids_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='request_time',
            new_name='created_at',
        ),
    ]
