# Generated by Django 4.2 on 2023-06-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_rename_request_time_userrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
