# Generated by Django 4.2.2 on 2023-07-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_rename_number_of_seqeunces_userrequest_number_of_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='process_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
