# Generated by Django 4.2.2 on 2023-10-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0017_remove_userrequest_process_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sequences', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
